---
- hosts: master
  become: yes 

  tasks:
  - name: create argocd namespace
    command: kubectl create namespace argocd
    ignore_errors: yes 
    environment: 
      KUBECONFIG: /home/ubuntu/.kube/config
  - name: Install ArgoCD
    command: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    environment:
      KUBECONFIG: /home/ubuntu/.kube/config

