name: cicd spring angular

on:
  push:
    branches: main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        -  name: checkout code source 
           uses: actions/checkout@v6

        - name: Build and test Spring boot
          run: | 
            cd springboot/app
            chmod +x mvnw
            ./mvnw clean package
            ./mvnw clean verify 

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Backend Docker image 
          run: |
            docker build -t ${{ vars.DOCKERHUB_USERNAME }}/spring-app-formation springboot/app
            docker push ${{ vars.DOCKERHUB_USERNAME }}/spring-app-formation

        - name: Build and Push Frontend Docker image 
          run: |
            docker build -t ${{ vars.DOCKERHUB_USERNAME }}/angular-app-devops angular-app
            docker push ${{ vars.DOCKERHUB_USERNAME }}/angular-app-devops 

        - name: Run with docker compose 
          run: |
            docker compose up -d 
            docker compose ps -a 